name: Pico Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: raspberrypi/pico-sdk:latest  # 使用官方Docker镜像

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive  # 确保克隆pico-sdk子模块

    - name: Build
      run: |
        cd adb_host  # 进入包含CMakeLists.txt的目录
        mkdir -p build
        cd build
        cmake .. -DPICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk
        make -j4

    - uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: adb_host/build/*.uf2  # 上传生成的固件
