name: Pico Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        
    - name: Install Toolchain
      run: |
        sudo apt update
        sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi
        
    - name: Build
      run: |
        mkdir build && cd build
        cmake .. -DPICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk
        make -j4
