name: Pico Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install ARM Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            gcc-arm-none-eabi \
            libnewlib-arm-none-eabi \
            build-essential \
            git \
            python3

      - name: Build Project
        run: |
          cd adb_host
          rm -rf build
          mkdir build
          cd build
          
          # 关键修改：添加 -DPICO_TOOLCHAIN_PATH 和禁用测试
          cmake .. \
            -DPICO_SDK_PATH=../../pico-sdk \
            -DPICO_TOOLCHAIN_PATH=/usr \
            -DCMAKE_C_COMPILER=arm-none-eabi-gcc \
            -DCMAKE_CXX_COMPILER=arm-none-eabi-g++ \
            -DCMAKE_ASM_COMPILER=arm-none-eabi-gcc \
            -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY  # 禁用可执行文件测试
          
          make -j4
