name: Pico Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install ARM Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            gcc-arm-none-eabi \
            libnewlib-arm-none-eabi \
            build-essential \
            git \
            python3

      - name: Build Project
        run: |
          # 设置工具链路径
          export PATH=$PATH:/usr/bin/arm-none-eabi/bin
          
          cd adb_host
          rm -rf build
          mkdir build
          cd build
          
          # 强制使用 ARM 工具链
          cmake .. \
            -DPICO_SDK_PATH=../../pico-sdk \
            -DCMAKE_C_COMPILER=arm-none-eabi-gcc \
            -DCMAKE_CXX_COMPILER=arm-none-eabi-g++ \
            -DCMAKE_ASM_COMPILER=arm-none-eabi-gcc
          
          make -j4
