name: Pico Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          
      - name: Force Update Submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive
          ls -la pico-sdk/external/pico_sdk_import.cmake

      - name: Install Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            gcc-arm-none-eabi \
            libnewlib-arm-none-eabi \
            build-essential

      - name: Build
        run: |
          cd adb_host
          rm -rf build
          mkdir build && cd build
          cmake .. \
            -DPICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk \
            -DPICO_BUILD_PICOTOOL=OFF \
            -DPICO_BUILD_DOCS=OFF \
            -DPICO_BUILD_EXAMPLES=OFF
          make -j4
