name: Pico Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: raspberrypi/pico-sdk:latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -DPICO_SDK_PATH=/pico-sdk
        make -j4

    - uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: build/*.uf2
