name: Pico Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            gcc-arm-none-eabi \
            libnewlib-arm-none-eabi \
            build-essential \
            binutils-arm-none-eabi
      - run: |
          cd adb_host
          rm -rf build CMakeCache.txt CMakeFiles
          cmake -B build \
            -DPICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk \
            -DPICO_PLATFORM=rp2040 \
            -DCMAKE_C_COMPILER=$(which arm-none-eabi-gcc) \
            -DCMAKE_ASM_COMPILER=$(which arm-none-eabi-gcc) \
            -DCMAKE_C_FLAGS="-mcpu=cortex-m0plus -mthumb" \
            -DCMAKE_CXX_FLAGS="-mcpu=cortex-m0plus -mthumb" \
            -DCMAKE_ASM_FLAGS="-mcpu=cortex-m0plus -mthumb" \
            -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY \
            -DPICO_BUILD_PICOTOOL=OFF \
            -DPICO_NO_HARDWARE=ON
          cmake --build build --target adb_host -j$(nproc --all)
