name: Pico Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - run: git submodule sync --recursive
      - run: git submodule update --init --force --recursive
      - run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            gcc-arm-none-eabi \
            libnewlib-arm-none-eabi \
            build-essential
      - run: |
          cd adb_host
          rm -rf build _deps
          cmake -B build \
            -DPICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk \
            -DPICO_BUILD_PICOTOOL=OFF \
            -DPICO_NO_HARDWARE=ON
          cmake --build build --parallel 4
