name: Pico Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            gcc-arm-none-eabi \
            libnewlib-arm-none-eabi \
            build-essential \
            python3 \
            python3-pip
          python3 -m pip install -r $GITHUB_WORKSPACE/pico-sdk/requirements.txt
      - run: |
          cd adb_host
          rm -rf build CMakeCache.txt CMakeFiles
          cmake -B build \
            -DPICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk \
            -DPICO_PLATFORM=rp2040 \
            -DPICO_COMPILER=pico_arm_gcc \
            -DPICO_TOOLCHAIN_PATH=/usr/bin \
            -DPICO_BUILD_PICOTOOL=OFF \
            -DPICO_NO_HARDWARE=ON
          cmake --build build --target adb_host -j4
