name: Pico Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/raspberrypi/pico-sdk:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: |
          cd adb_host
          mkdir build && cd build
          cmake .. -DPICO_SDK_PATH=/pico-sdk
          make -j4

      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: adb_host/build/*.uf2
