name: Pico Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/raspberrypi/pico-sdk:latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -DPICO_SDK_PATH=/pico-sdk
        make -j4

    - uses: actions/upload-artifact@v4  # 关键修改处
      with:
        name: pico-firmware
        path: build/*.uf2
