name: Pico Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive  # 确保子模块（如 pico-sdk）被克隆

      - name: Install ARM Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential

      - name: Build Project
        run: |
          cd adb_host
          mkdir build
          cd build
          cmake .. -DPICO_SDK_PATH=../../pico-sdk
          make -j4
