name: Pico Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PICO_SDK_PATH: ${{ github.workspace }}/pico-sdk
      PICO_PLATFORM: rp2040
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            gcc-arm-none-eabi \
            libnewlib-arm-none-eabi \
            build-essential \
            binutils-arm-none-eabi
      - run: |
          cd adb_host
          rm -rf build CMakeCache.txt CMakeFiles
          cmake -B build \
            -DPICO_SDK_PATH=$PICO_SDK_PATH \
            -DPICO_PLATFORM=$PICO_PLATFORM \
            -DCMAKE_C_COMPILER=arm-none-eabi-gcc \
            -DCMAKE_ASM_COMPILER=arm-none-eabi-gcc \
            -DCMAKE_C_FLAGS="-mcpu=cortex-m0plus -mthumb" \
            -DCMAKE_CXX_FLAGS="-mcpu=cortex-m0plus -mthumb" \
            -DCMAKE_ASM_FLAGS="-mcpu=cortex-m0plus -mthumb" \
            -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY \
            -DPICO_BUILD_PICOTOOL=OFF \
            -DPICO_NO_HARDWARE=ON \
            -DPICO_SDK_FETCH_FROM_GIT=OFF
          cmake --build build --target adb_host -j4
