name: Pico Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            cmake \
            gcc-arm-none-eabi \
            libnewlib-arm-none-eabi \
            git \
            build-essential

      - name: Build
        run: |
          cd adb_host
          mkdir build && cd build
          cmake .. -DPICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk
          make -j4
