name: Pico CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Install Toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          gcc-arm-none-eabi \
          libnewlib-arm-none-eabi \
          build-essential

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. \
          -DPICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk \
          -DPICO_BOARD=pico

    - name: Build
      run: |
        cd build
        make -j$(nproc)

    - uses: actions/upload-artifact@v4
      if: success()
      with:
        name: pico-firmware
        path: build/*.uf2
