name: Pico Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            gcc-arm-none-eabi \
            libnewlib-arm-none-eabi \
            build-essential
      - run: |
          cd adb_host
          rm -rf build CMakeCache.txt CMakeFiles
          cmake -B build \
            -DPICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk \
            -DPICO_BUILD_PICOTOOL=OFF \
            -DPICO_BUILD_DOCS=OFF \
            -DPICO_BUILD_EXAMPLES=OFF \
            -DPICO_NO_HARDWARE=ON \
            -DPICO_PLATFORM=rp2040
          cmake --build build --target adb_host
